name: Deploy Backend

on:
  push:
    branches:
      - main # Or any branch of your choice, e.g., 'develop'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Or whichever version of Node.js you're using

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Deploy to Server
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }} # Make sure to set the MongoDB URI in your GitHub secrets
        run: |
          npm run build
          pm2 restart your-app # Example: restart the app on your server
